version: "3"

# Define the network used by all services in this setup
networks:
  image-challenge-network:
    driver: bridge

services:
  # Backend service configuration
  backend:
    build: ./backend
    ports:
      - "8002:8002"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - image-challenge-network
    environment:
      POSTGRES_DB: image_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db

  # Frontend service configuration
  frontend:
    build: ./frontend
    ports:
      - "3002:3000"
    networks:
      - image-challenge-network
    environment:
      # URL to the backend service (http://nginx/.. in prod)
      REACT_APP_API_URL: "http://localhost:8002"

  # Adminer (Database management interface)
  adminer:
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - image-challenge-network

  # Database service configuration
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: image_data
    # Mounts the named volume 'pgdata' at the required path
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - image-challenge-network
    healthcheck:
      # Health check to ensure DB is ready
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

# Volumes section for defining persistent storage
# Named volume 'pgdata' used for storing PostgreSQL data persistently
volumes:
  pgdata:
